### ISSUE TITLE
Type tutorial how to install package and define dependencies

### ISSUE THREAD

**Issue by janbarasek** [mathematicator-core/tokenizer#2]
This package is relatively complicated and some beginners have trouble with install.

Examples:

- https://forum.nette.org/cs/32460-nette-project-composer-odmita-instalovat-mathematicator-core-tokenizer
- https://forum.nette.org/cs/32528-nastaveni-di-v-neonu-pro-plugin-z-composeru

I think in README should be some tutorial how install basic Nette sandbox with Mathematicator dependencies and with some sample project.

**Comment by flokixdev** [comment]
@janbarasek The first problem is solved as we have stable/unstable versions.

For the second one, there is a link to DI in README, I think that it's enough.

The only thing that is missing is how to extension Nette app container with Mathematicator package dependencies.

**Comment by janbarasek** [comment]
I fixed the problem with addictions. The configuration is newly solved via DI Extension.
